--- #YAML:1.0
name:               Data-FetchPath
version:            0.02
abstract:           "eval"able paths to your complex data values
author:
    - Curtis "Ovid" Poe <ovid@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Most:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
